# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.joshiegemfinder.dragonlootadvancednetheritepatch
archives_base_name=dragon_loot_advanced_netherite_patch

# Version Ranges
fabric_api_version_range=>=0.80.0+1.20.1
advanced_netherite_version_range=>=2.1.3-1.20.1
dragonloot_version_range=>=1.1.4
advanced_netherite_medieval_weapons_version_range=>=1.0.0


# Dependencies
fabric_api_version=0.92.7+1.20.1
cloth_config_version=11.0.99
mod_menu_version=7.0.0
advanced_netherite_version=fabric-2.1.3-mc1.20.1
dragonloot_version=1.1.4+1.20.1
medieval_weapons_version=1.4.8+1.20.1
advanced_netherite_medieval_weapons_version=1.0.0+1.20.1+fabric